### ISSUE TITLE
見た目：問題10の枠の表示がずれてる

### ISSUE THREAD

**Issue by bvv-1** [ut-code/typing-game#111]
他の問題では枠をそもそも表示させたくない

**Comment by chvmvd** [comment]
script.jsのword_numをBasic.tsxでuseStateで変数を作って、script.jsにも渡してあげれば、Basic.tsxで変数を使えるからそこで、{word_num===1 && <hoge>hoge</hoge>}のようにすれば、できるかも。

**Comment by bvv-1** [comment]
やっぱり問題10は消す方向で…
