### ISSUE TITLE
Resultの「同問題順位」を表示させる

### ISSUE THREAD

**Issue by baar-vendel** [ut-code/typing-game#113]
真似してやってみたんですがReactわかりません...

**Comment by chvmvd** [comment]
なるほど。
キーボード配列ごとも作ったら、面白そう。

**Comment by chvmvd** [comment]
データベースにどの問題の結果かとかの情報とかはあるんでしたっけ？
あれば、すぐにできるかも。
問題ごとにソートして、それをmap関数でReact風に書けばいけるかな？
後は、[このページ](https://learn.utcode.net/docs/web-servers/node-js/)のWindowsとMacの選択するところみたいに、<Tab>と<Tabitem>みたいなので書けば分かりやすいかな。

**Comment by baar-vendel** [comment]
> データベースにどの問題の結果かとかの情報とかはあるんでしたっけ？
> あれば、すぐにできるかも。
> 問題ごとにソートして、それをmap関数でReact風に書けばいけるかな？と思ってます。
> 後は、[このページ](https://learn.utcode.net/docs/web-servers/node-js/)のWindowsとMacの選択するところみたいに、とみたいなので書けば分かりやすいかな。

あります（qnumberじゃなくてproblemってカラム名）
ちょっと調べてみます

**Comment by chvmvd** [comment]
やったー！
そしたら、だいぶ楽だ。

**Comment by baar-vendel** [comment]
ごめんなさい、submitのときにqnumber登録するの忘れてただけでした...
ランキングの表示は時間的にやめておきます；；
