### ISSUE TITLE
Renderが15分すぎると、スリープしてしまう。

### ISSUE THREAD

**Issue by chvmvd** [ut-code/typing-game#121]
Renderの仕様で、15分間アクセスがないとスリーブしてしまう。そのため、バックエンドの起動に時間がかかってしまっている。

これは、定期的にアクセスしてあげることで解決できそう。

**Comment by chvmvd** [comment]
[ここ](https://qiita.com/ppputtyo/items/2ab44303dcfabeb7b23e)を参考に解決

**Comment by chvmvd** [comment]
完璧ではありませんが、とりあえずこれで行きます。
https://github.com/ut-code/translate-braille/pull/32

**Comment by bvv-1** [comment]
解決？

**Comment by chvmvd** [comment]
これなんだけど、基本は 14 分ごとにやってくれるんだけど、必ずしも 14 分ごとではないんですよ…
だから、まあまあの確率でスリープに入ることがある…

**Comment by chvmvd** [comment]
こんな感じで、23 分後になったりする…
ちなみに、これは仕様なので、他の方法を考えたほうが良さそう。
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/104971044/236581841-5ed1c50c-891c-4211-ad45-06343ff5ac8f.png">

**Comment by bvv-1** [comment]
とりあえずrenderawake.ymlを作成しました

**Comment by chvmvd** [comment]
ナイス！
