### ISSUE TITLE
結果画面がほかの人のになる（同時にプレイする・サブミットするとなる？）

### ISSUE THREAD

**Issue by bvv-1** [ut-code/typing-game#124]
直し方わかりません；；

**Comment by chvmvd** [comment]
おそらく、node-localStorageはサーバー上にデータを保存してるので、ブラウザ側のlocalStorageに保存すれば解決しそうな気がします。

**Comment by bvv-1** [comment]
これ直ったかな？
代わりにlocalStorageいじられて高得点submitされたりするんでしょうか…

**Comment by chvmvd** [comment]
直ってます！
確かに、localStorage 直接いじったらできますけど、どうしようもない気がします。
それの対策はけっこう時間がかかりそう。
