### ISSUE TITLE
データベースからデータを拾ってくるのに時間がかかる旨を表示する。

### ISSUE THREAD

**Issue by chvmvd** [ut-code/typing-game#129]
なぜ始まらないのか分からない人が多いと思われるので、loading...などを画面に表示した方が良さそう。

**Comment by bvv-1** [comment]
ページ遷移後すぐにPlay押すとこれが終わらないのか（ずっとuseStateのせいだと思ってました）
その間は入力を受け付けないようにしたいけど意外と実装複雑そう…

**Comment by chvmvd** [comment]
単純に response が来るまで、Progress を表示すれば良いような気がします。
MUI だとこんな感じのがある。https://mui.com/material-ui/react-progress/
Bootstrap も似たのがあるはず。

**Comment by bvv-1** [comment]
詳しく調べてないのですが、レンダリングを止めておかないと、Progressを表示している間にもキーボードの入力を監視して始まってしまいそうな気もします

**Comment by chvmvd** [comment]
確かに、そうですね。
まあ、とりあえず Progress を表示してその後考えましょう。

**Comment by chvmvd** [comment]
いやでも、多分大丈夫な気がします。問題が来ないと始まらなかったような気がする。

**Comment by bvv-1** [comment]
questionsの長さが長くなるまでスピナーが表示されるようにしました
