### ISSUE TITLE
開発環境だとCORSが原因でbackendが動かない

### ISSUE THREAD

**Issue by bvv-1** [ut-code/typing-game#132]
render.yamlでうまくやってた気がするんですが、いじって壊す自信があるので一旦コメントアウトしちゃいました
任せます！！！！！！

**Comment by bvv-1** [comment]
```
// app.use(cors({ origin: process.env["WEB_ORIGIN"] })) // 本番環境
app.use(cors()) // 開発環境
```

**Comment by chvmvd** [comment]
バックエンドの `.env` ファイルに `WEB_ORIGIN` 環境変数がセットされてるか確認して欲しいです。

**Comment by bvv-1** [comment]
お騒がせしました
localhostと書くべきところが127...になってました

**Comment by chvmvd** [comment]
あれ、localhost か。
設定ファイルミスってたかもなので、後で直します。
