### ISSUE TITLE
ランキングをつくる。ニックネームを使って。

### ISSUE THREAD

**Issue by chvmvd** [ut-code/typing-game#14]

**Comment by baar-vendel** [comment]
https://github.com/ut-code/typing-game/pull/23#issue-1361093702
テーブルの作成、結果表示のページなどを進めてみました。
次やることは、
・word_num === questions.lengthでresults.ejsに飛ぶように実装
・ランキングに新しいレコードをCreateする機能を実装
・リザルト画面表示の充実

**Comment by baar-vendel** [comment]
・word_num === questions.lengthでresults.ejsに飛ぶように実装
・ランキングに新しいレコードをCreateする機能を実装

の二点が完了しました！

**Comment by baar-vendel** [comment]
読み込むたびにスコアがsubmitされるバグを修正しないといけないですね

**Comment by chvmvd** [comment]
そうですねw

**Comment by baar-vendel** [comment]
[https://github.com/ut-code/typing-game/issues/35#issue-1381744174](https://github.com/ut-code/typing-game/issues/35#issue-1381744174) 
こちらへ移行
