### ISSUE TITLE
【！】デプロイ先でバックエンドが動いていない

### ISSUE THREAD

**Issue by bvv-1** [ut-code/typing-game#172]
https://typing.utcode.net/

.envの中身を
WEB_ORIGIN=http://localhost:5173
↓
WEB_ORIGIN=http://localhost:4173
に直すといけました。

本番環境と開発環境でつなぎ替えるという部分がうまくいっていない予感がします。

**Comment by bvv-1** [comment]
render.yamlの設定周りだと思うのでお願いします

**Comment by bvv-1** [comment]
本番環境でnpm run build→npm run startすると、4173になりませんか。

**Comment by chvmvd** [comment]
本番環境では、おそらく `npm run start` はしないはずなので、関係ないはずです。

**Comment by chvmvd** [comment]
`npm run start` はローカルでテストするためのもののはずです。ここらへんは、menu のものを見ると良いです。
本当は、ローカルで動くように `http://localhost:4173` も加えた方が良いのですが、時間がないのでやっていません。

**Comment by bvv-1** [comment]
あ、そうだったんですね
だとすると原因はなんでしょう。api.typing.utcode.netが繋がってないとか？

**Comment by chvmvd** [comment]
よくわからないです。
今回変えたのは、ドメインだけでその前は動いていたので…
バックエンドも動いているはず。CORS でブロックされてる…最悪、CORS を消せばいいけど。

**Comment by chvmvd** [comment]
なぜか直りました！原因不明です。
