### ISSUE TITLE
Homeで打ち込んだニックネームと問題番号を有効活用する

### ISSUE THREAD

**Issue by baar-vendel** [ut-code/typing-game#35]
・Home.tsxで送った内容を、main.jsを経由してBasicのscript.jsで読み込む
・main.jsのgetQuestionsでqnumberを使った問題読み込み
・main.jsのsubmitRankingにユーザーネームを使うようにする

**Comment by baar-vendel** [comment]
results.ejsを.tsxにしないとreact bootstrapが使えなくて、
resultsでも変数の受け渡しがあるからこれが解決しないと厳しい。

**Comment by baar-vendel** [comment]
いろいろ書いたけど普通にmain.jsで変数管理できるようにしたら解決
ただし空白にすると名前も空白になるのはなんとかしたい

**Comment by chvmvd** [comment]
デフォルト値を設定するとかで解決できるかな？
