### ISSUE TITLE
問題作成：ページ内ページのように/basicの画面が小さい枠で出来上がっていく

### ISSUE THREAD

**Issue by baar-vendel** [ut-code/typing-game#38]

**Comment by baar-vendel** [comment]
・innerHTMLで問題文をWebページに翻訳する
・問題文のsyntax highlightをそれらしく表示する

**Comment by chvmvd** [comment]
syntax highlightはHTMLのCodeBlockとか使えばすぐいけそうですね〜

**Comment by baar-vendel** [comment]
教育用はやっぱりやめて、ページ内ページみたいに/basicの画面が組み上がっていく問題にしたほうが面白そう！と思いついた

**Comment by chvmvd** [comment]
さっき見つけたのだけど、これが参考になるかも。詳しくは知りません。
https://github.com/ut-code/pwa-maker

**Comment by baar-vendel** [comment]
ありがとう〜〜

**Comment by baar-vendel** [comment]
TSXファイルだからか、iframeだったりmonaco-editorだったりが作動しないからもっと愚直にやるしかないかも...
エディタには一旦@monaco-editor/reactを使ってみます。

**Comment by baar-vendel** [comment]
これだと書き込むってことが出来なそうなので、文字として表示するだけにします、すいません

**Comment by baar-vendel** [comment]
解決
