### ISSUE TITLE
react bootstrapを使って整形するためにresults.ejsを.tsx形式に変更

### ISSUE THREAD

**Issue by baar-vendel** [ut-code/typing-game#44]
results.ejsを.tsxにしないとreact bootstrapが使えなくて、
resultsでも変数の受け渡しがあるからこれが解決しないと厳しい。

_Originally posted by @baar-vendel in https://github.com/ut-code/typing-game/issues/35#issuecomment-1256049043_

**Comment by baar-vendel** [comment]
変えるべき箇所が結構おおくて難しそう
現状、results.ejsはfetchAPIでhtmlを受け取ってinnerHTMLで/basic内で表示している

**Comment by chvmvd** [comment]
Reactで別のURL上にすればすぐできそう。
/resultsでCookieのユーザーネームに対応したデータをサーバーから拾ってくれば行ける気がする。

**Comment by chvmvd** [comment]
詳しい人に聞いたら、Cookie関連はけっこうだるいらしい…
