### ISSUE TITLE
result画面をreact bootstrapで整形する

### ISSUE THREAD

**Issue by baar-vendel** [ut-code/typing-game#45]
/resultにアクセスすると一応見れます

**Comment by chvmvd** [comment]
Reactだと変数はuseStateを使うとうまくいきそう。
繰り返し処理はmapメソッドを使えばうまくいきそう。
両方とも詳しくはut.code(); Learnを参照

**Comment by chvmvd** [comment]
追伸
JSX内でJavaScriptを使うには{}を使うとできる。

**Comment by chvmvd** [comment]
Reactを使うのを避けるなら、最悪createElementしてappendChildするって手もありそう。

**Comment by baar-vendel** [comment]
createElementしてappendChildって調べたんですが、div要素とか作ったら結局React bootstrap使えなくない？
あとReactわからなすぎて辛い...

**Comment by baar-vendel** [comment]
useEffectでfetchAPI使えることが判明し、解決の糸口が見えてきました！

**Comment by chvmvd** [comment]
確かに、createElementだとReactの機能のbootstrapは使えないわ。
直接Reactで書くのが良さそう。

**Comment by chvmvd** [comment]
> useEffectでfetchAPI使えることが判明し、解決の糸口が見えてきました！

そうだね。
script.jsはuseEffect内にいれて、使えるようにしてた。
script.jsをReactに入れてるコードあたりがが参考になるかも。

**Comment by baar-vendel** [comment]
https://github.com/ut-code/typing-game/pull/68#issue-1403868376

あとはscore, time, username, qnumber等の変数がちゃんと保管・受け渡しできれば一件落着です

**Comment by chvmvd** [comment]
いい感じ！
ありがとう！
よくよく見たら、useEffectの参考になるのこのリポジトリ内になかった…
もう遅いけど、前に作ったこれが参考になりそう。
https://github.com/ut-code/utcode-learn/blob/54ac4b1a2d14bb212febaa1d29cecbb65e444711/docs/4-advanced/04-react/_samples/todo-database2/frontend/src/App.tsx#L16

**Comment by chvmvd** [comment]
よくよく考えたら、script.jsの中に書けば良かっただけか。そういえば、script.jsはasync関数になってた。

**Comment by baar-vendel** [comment]
一旦closeしちゃう、あとはビジュアルの問題だけ
