### ISSUE TITLE
ロゴを作成する、ファビコンを設定する

### ISSUE THREAD

**Issue by baar-vendel** [ut-code/typing-game#48]

**Comment by chvmvd** [comment]
ごめん。
Reactの中身は、通常のHTMLとはheadを設定できないのと、コメントの書き方が違う(これは、VSCodeが勝手にやるから気づかないけど)っていう違いがある。

**Comment by chvmvd** [comment]
ちなみに、arcのフォルダがある階層のindex.htmlが本体になっていて、それの中に全てのReactの中身が入っているから、実はそれをいじればheadの中身(favicon)などを設定できる。
よく分からなかったから、後ですぐできるから言ってもらえれば。

**Comment by chvmvd** [comment]
https://www.shopify.com/jp/tools/logo-maker

ロゴメーカー

**Comment by chvmvd** [comment]
ボツロゴ

[HatchfulExport-All(1).zip](https://github.com/ut-code/typing-game/files/9837124/HatchfulExport-All.1.zip)

![logo](https://user-images.githubusercontent.com/104971044/197149638-724e18e7-f162-4b0b-a0eb-b2015e73f33c.png)

**Comment by chvmvd** [comment]
ボツロゴ
[typing-game-logo-zip-file.zip](https://github.com/ut-code/typing-game/files/9838245/typing-game-logo-zip-file.zip)
![logo-color](https://user-images.githubusercontent.com/104971044/197176531-ab8ac859-8f04-4145-bf74-7d15f1790b16.svg)

**Comment by baar-vendel** [comment]
ナイス！
