### ISSUE TITLE
デプロイする

### ISSUE THREAD

**Issue by chvmvd** [ut-code/typing-game#51]
現状、ちゃんと設定してもRenderがポート番号を正しく認識してくれないので、render.yamlで頑張るしかないらしい。

**Comment by chvmvd** [comment]
現状、フロントエンドはデプロイできていて、バックエンドをできた。
しかし、データベースからデータをとれていないように思われる。

**Comment by baar-vendel** [comment]
これやばそうですか...？

**Comment by chvmvd** [comment]
最悪、デプロイ方法を変えればできる。つまり、前動いてた方法を使えばいける。
とりあえず、今日の夜もう一回やるつもりなので、それでやってだめだったら、考えます。

**Comment by chvmvd** [comment]
多分、できました。
`VITE_API_ENDPOINT` が `https://server-o13g.onrender.com/` になっていたのを、`https://server-o13g.onrender.com` に変えたら、なぜか動きました。`/` が入っていると、うまく動かなかったようです。

**Comment by chvmvd** [comment]
resolved with #106 #105
