### ISSUE TITLE
単語の間にスペースがあるのが、分かりづらいので、分かりやすくした方が良さそう。

### ISSUE THREAD

**Issue by chvmvd** [ut-code/typing-game#59]

**Comment by baar-vendel** [comment]
アイディアなにかあればほしい...

**Comment by chvmvd** [comment]
うーん。
「A B C」の問題が分かりにくかっただけだから、この問題を消すぐらいしか思いつかない…
後は、次の入力を表示する機能を付けるとかか。

**Comment by baar-vendel** [comment]
時間足りなそうなのでこのままで行きましょう

**Comment by chvmvd** [comment]
A B Cの問題のように、紛らわしい問題を無くせば、大丈夫な気がします。
単語間のスペースとかは、わかるはずなので。
