### ISSUE TITLE
不正なbodyタグの使用

### ISSUE THREAD

**Issue by keyhr** [ut-code/typing-game#63]
タイピングゲームのページ読み込み時に以下のエラーが出ました

<img width="501" alt="Screen Shot 2022-10-02 at 13 07 13" src="https://user-images.githubusercontent.com/96811548/193437376-1fde6e0d-6508-4338-82a3-a114705089df.png">

**Comment by chvmvd** [comment]
ありがとう!

**Comment by keyhr** [comment]
Fixed with #64
