### ISSUE TITLE
Warning: Cannot update a component (`Basic`) while rendering a different component (`App`).

### ISSUE THREAD

**Issue by keyhr** [ut-code/typing-game#65]
`/basic` を読み込んだときに警告が出てきました。

<img width="500" alt="Screen Shot 2022-10-02 at 13 14 38" src="https://user-images.githubusercontent.com/96811548/193437548-ae095eba-045e-4c61-822b-494361df05e2.png">

以下スタックトレースです。

<img width="493" alt="Screen Shot 2022-10-02 at 13 13 52" src="https://user-images.githubusercontent.com/96811548/193437552-cce797e9-eac6-48b9-ba19-6b4a211aa87a.png">

**Comment by chvmvd** [comment]
これは、Basic.tsxの子要素をKeyboardコンポーネントによって、操作してるから起こっている気がします。
