### ISSUE TITLE
スコアの算出式を改善

### ISSUE THREAD

**Issue by baar-vendel** [ut-code/typing-game#77]

**Comment by ts5-25** [comment]
timeLeft * Math.floor((correct / (miss + correct + 1)) * 100 + Math.sqrt(correct))
timeLeft * Math.floor(correct**2 / (miss + correct + 1))

**Comment by baar-vendel** [comment]
f() = w1\*完了率 * w2\*難度 * w3\*正答率 * w4\*タイピング速度
_w_ は重み、あとで調整

- 完了率は完了問題数/全問題数
- 難度は指数関数的な傾きにしたい、算出法は不明
- 正答率は文字通りだが、正答を重視して正答の二乗/(正答+ミス+1) https://github.com/ut-code/typing-game/issues/77#issuecomment-1287589104
- タイピング速度は文字通り

**Comment by baar-vendel** [comment]
足し算に変更、あとはテストを繰り返してもらって感覚に合うか試す
